<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Phoodab.Application/Phoodab.Application.csproj" />
    <ProjectReference Include="../Phoodab.Domain/Phoodab.Domain.csproj" />
  </ItemGroup>
</Project>
