/**
 * This file is generated by openapi-typescript from /swagger/v1/swagger.json.
 * Do not edit manually.
 */

export interface paths {
  '/health': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': {
              status: string;
            };
          };
        };
      };
    };
  };
  '/version': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': {
              version: string;
            };
          };
        };
      };
    };
  };
}
